image: java:latest

stages:
  - scan

scan:
  stage: scan
  script:
    - pwd
    - ls -al
    - echo $JAVA_HOME
    - cd CxConsolePlugin
    - pwd
    - ls -al
    - chmod 755 runCxConsole.sh
    - ./runCxConsole.sh Scan -v -CxServer http://cxsample.eastus.cloudapp.azure.com -projectName "CxServer\WebGoat-8.0.0.M25" -CxUser "admin@cx" -CxPassword "CheckMarx@01" -Locationtype folder -locationpath ../. -locationPathExclude "webgoat-server,webwolf,scripts,platformQuickStarts,CxConsolePlugin" -Preset "Checkmarx Default"  -incremental
  artifacts:
    paths: [gl-cm-report.json]
